name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
        
    - name: install yarn
      run: |
        npm install -g yarn
        
    - name: startup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf /opt/investment-web/*
          rm -rf /root/.pm2/logs/main-error.log
          rm -rf /root/.pm2/logs/main-out.log

    - name: Build
      run: |
        yarn install
        yarn build
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "./build/*"
        target: "/opt/investment-web/"

    - name: startup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/investment-web/
          cp ./build/index.html ./build/404.html
          pm2 stop /usr/local/bin/http-server -- ./build  -p 8080
          pm2 start /usr/local/bin/http-server -- ./build  -p 8080
